SELECT
 MACH.MCH_NUMBER
,EV.EVS_START
,EV.EVS_END
,EV.MAT_SAP_CODE
,EVS_REAL_QTY
FROM BR_FS_CAR_FAC_PCS02.DC_EVENTS AS EV
INNER JOIN BR_FS_CAR_FAC_PCS02.MD_MACHINES AS MACH
ON EV.MCH_CODE = MACH.MCH_CODE AND EV.PP_CODE = MACH.PP_CODE
WHERE
EV.EV_CODE = 'PROD' AND EV.EV_SUBCODE = 'MACH' AND EV.EVS_END BETWEEN '{0}' AND '{1}' AND EV.PP_CODE = 'CF2'
UNION ALL
SELECT
 MACH.MCH_NUMBER
,EV.EVS_START
,EV.EVS_END
,EV.MAT_SAP_CODE
,EVS_REAL_QTY
FROM BR_FS_CAR_FAC_PCS02.HIS_EVENTS AS EV
INNER JOIN BR_FS_CAR_FAC_PCS02.MD_MACHINES AS MACH
ON EV.MCH_CODE = MACH.MCH_CODE AND EV.PP_CODE = MACH.PP_CODE
WHERE
EV.EV_CODE = 'PROD' AND EV.EV_SUBCODE = 'MACH' AND EV.EVS_END BETWEEN '{0}' AND '{1}' AND EV.PP_CODE = 'CF2'